export enum Occupation {
    Không = "Không",
    Nhân_viên_tẩm_quất = "Nhân viên tẩm quất",
    Công_tác_xã_hội = "Công tác xã hội",
    Cán_bộ_hội = "Cán bộ hội",
    Giáo_viên = "Giáo viên",
    Âm_nhạc = "Âm nhạc",
    Kinh_doanh = "Kinh doanh",
    Bán_hàng_Online = "Bán hàng Online",
    Trực_điện_thoại = "Trực điện thoại",
    Phiên_dịch = "Phiên dịch",
    Chăn_nuôi = "Chăn nuôi",
    Thủ_công = "Thủ công",
    Nông_nghiệp = "Nông nghiệp",
    Nghề_tự_do = "Nghề tự do",
    Nghề_khác = "Nghề khác",
}
